---
# Configuration tasks for DigitalOcean Agent

- name: Create DigitalOcean Agent configuration directory
  ansible.builtin.file:
      path: /etc/do-agent
      state: directory
      owner: root
      group: root
      mode: "0755"
  become: true

- name: Generate DigitalOcean Agent configuration
  ansible.builtin.template:
      src: etc/do-agent/do-agent.yaml.j2
      dest: /etc/do-agent/do-agent.yaml
      owner: root
      group: root
      mode: "0600"
  become: true
  notify: "do: restart do agent"
  no_log: "{{ do_no_log_api_token | default(true) }}"
  when: do_custom_config_enabled | default(false)

- name: Find leftover DigitalOcean Agent configuration backups
  ansible.builtin.find:
      paths: /etc/do-agent
      patterns: "do-agent.yaml.*"
      excludes: "do-agent.yaml"
      file_type: file
  register: do_config_backups
  become: true

- name: Remove leftover DigitalOcean Agent configuration backups
  ansible.builtin.file:
      path: "{{ item.path }}"
      state: absent
  loop: "{{ do_config_backups.files }}"
  loop_control:
      label: "{{ item.path }}"
  become: true

- name: Create environment file for custom settings
  ansible.builtin.template:
      src: etc/default/do-agent.j2
      dest: /etc/default/do-agent
      owner: root
      group: root
      mode: "0600"
  become: true
  notify: "do: restart do agent"
  no_log: "{{ do_no_log_api_token | default(true) }}"
  when: do_api_token != "" or do_custom_config_enabled | default(false)
