---
dependency:
    name: galaxy
    options:
        requirements-file: requirements.yml

driver:
    name: docker

platforms:
    - name: tailscale-ubuntu2204
      image: geerlingguy/docker-ubuntu2204-ansible:latest@sha256:9ac75f2cd2b4fc6ddc9d5166a24adfe3d1cf6a49911ee5d75fd63a853bdaadf9
      command: ""
      volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
      cgroupns_mode: host
      privileged: true
      pre_build_image: true

    - name: tailscale-ubuntu2404
      image: geerlingguy/docker-ubuntu2404-ansible:latest@sha256:3394e335df58c961c00b78ae601ef30cdd7463b112f21b0c5f78674a70526302
      command: ""
      volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
      cgroupns_mode: host
      privileged: true
      pre_build_image: true

    - name: tailscale-debian12
      image: geerlingguy/docker-debian12-ansible:latest@sha256:a131e3b7a9a38dda40e98b49b39d6200ffab0ad853c714a513f5eea41bab9a25
      command: ""
      volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
      cgroupns_mode: host
      privileged: true
      pre_build_image: true

provisioner:
    name: ansible
    config_options:
        defaults:
            interpreter_python: auto_silent
            callbacks_enabled: profile_tasks, timer
            stdout_callback: ansible.builtin.default
            result_format: yaml
    inventory:
        host_vars:
            tailscale-ubuntu2204:
                ansible_user: root
            tailscale-ubuntu2404:
                ansible_user: root
            tailscale-debian12:
                ansible_user: root

verifier:
    name: ansible

scenario:
    name: default
    test_sequence:
        - dependency
        - cleanup
        - destroy
        - syntax
        - create
        - prepare
        - converge
        - idempotence
        - side_effect
        - verify
        - cleanup
        - destroy
